services:
  golgari-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    command: "npm run start:debug"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - ENV=LOCAL
      - PORT=3000
      - LOG_LEVEL=info
      - PRETTY_PRINT=false
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_DATABASE=
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - PRIVATE_KEY=
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - golgari_network
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
  golgari-database:
    image: postgres:16.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    networks:
      - golgari_network
networks:
  golgari_network:
    external: false
